# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

# from tkinter import *
# Explicit imports to satisfy Flake8
import datetime
import threading
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, StringVar, END, ttk, Label, Frame, BOTH

from tkcalendar import Calendar

from GUI import guiutils
from KairosBot import KairosBot


class GUI:

    def setUserData(self, id, password):
        self.userId = id
        self.password = password

    def performInputAction(self, id, password, window):
        window.destroy()
        self.setUserData(id, password)
        self.startGUI2()

    def performBookAction(self, window, cal):
        window.destroy()
        self.date = cal.selection_get()
        self.startGUI3()

    def startGUI1(self):
        window = Tk()

        window.geometry("464x853")
        window.title("KairosBot")
        window.configure(bg="#FFFFFF")

        canvas = Canvas(
            window,
            bg="#FFFFFF",
            height=853,
            width=464,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(
            file=guiutils.relative_to_assets("image_1.png"))

        smaller_image = image_image_1.subsample(5, 5)

        image_1 = canvas.create_image(
            220.0,
            430.0,
            image=smaller_image
        )

        canvas.create_text(
            219.5,
            411.0,
            anchor="nw",
            text="Hi there!",
            fill="#FFFFFF",
            font=("SFProDisplay Semibold", 20 * -1)
        )

        canvas.create_text(
            123.0,
            441.0,
            anchor="nw",
            text="Let’s Get Started",
            fill="#FFFFFF",
            font=("SFProDisplay Heavy", 34 * -1)
        )

        entry_image_1 = PhotoImage(
            file=guiutils.relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            235.0,
            556.0,
            image=entry_image_1
        )

        entry1Var = StringVar()

        entry_1 = Entry(
            bd=0,
            bg="#FFFFFF",
            highlightthickness=0,
            textvariable=entry1Var
        )
        entry_1.place(
            x=100.0,
            y=519.0,
            width=268.0,
            height=72.0
        )

        entry_1.insert(END, 'Student ID')
        entry_1.bind("<Button-1>", guiutils.delete_text_on_callback)

        entry_image_2 = PhotoImage(
            file=guiutils.relative_to_assets("entry_2.png"))
        entry_bg_2 = canvas.create_image(
            235.0,
            643.0,
            image=entry_image_2
        )

        entry2Var = StringVar()

        entry_2 = Entry(
            bd=0,
            bg="#FFFFFF",
            highlightthickness=0,
            textvariable=entry2Var,
            show="*",
        )
        entry_2.place(
            x=100.0,
            y=607.0,
            width=270.0,
            height=70.0
        )
        entry_2.insert(END, 'password')
        entry_2.bind("<Button-1>", guiutils.delete_text_on_callback)

        button_image_1 = PhotoImage(
            file=guiutils.relative_to_assets("button.png"))

        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.performInputAction(entry1Var.get(), entry2Var.get(), window),
            relief="flat"
        )

        button_1.place(
            x=180.0,
            y=704.0,
            width=95.0,
            height=41.0
        )

        window.resizable(False, False)
        window.mainloop()

    def startGUI2(self):
        window = Tk()

        window.geometry("474x628")
        window.configure(bg="#FFFFFF")

        canvas = Canvas(
            window,
            bg="#FFFFFF",
            height=628,
            width=474,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)
        canvas.create_rectangle(
            0.0,
            0.0,
            474.0,
            628.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            32.0,
            32.0,
            anchor="nw",
            text="KairosBot",
            fill="#000000",
            font=("Montserrat Bold", 32 * -1)
        )

        canvas.create_rectangle(
            0.0,
            132.0,
            474.0,
            192.0,
            fill="#FAFAFA",
            outline="")

        canvas.create_text(
            32.0,
            152.0,
            anchor="nw",
            text="Prenotazione lezioni dell’intera giornata",
            fill="#000000",
            font=("Roboto", 13 * -1)
        )

        button_image_1 = PhotoImage(
            file=guiutils.relative_to_assets("button_book.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.performBookAction(window, cal),
            cursor="hand"
        )
        button_1.place(
            x=47.0,
            y=522.0,
            width=380.0,
            height=44.0
        )

        canvas.create_rectangle(
            0.0,
            132.0,
            474.0,
            133.0,
            fill="#F1F1F1",
            outline="")

        canvas.create_text(
            32.0,
            86.0,
            anchor="nw",
            text="Prenotazione",
            fill="#111111",
            font=("Roboto", 16 * -1)
        )

        today = datetime.date.today()

        mindate = today
        maxdate = today + datetime.timedelta(days=6)
        cal = Calendar(window, font="Arial 14", selectmode='day', locale='ita',
                       mindate=mindate, maxdate=maxdate, disabledforeground='red', foreground='black',
                       weekendbackground='white', disableddaybackground='gray',
                       firstweekday="monday", cursor="hand")
        cal.pack(padx=10, pady=200)

        for i in range(6):
            cal._week_nbs[i].destroy()

        s = ttk.Style(window)
        s.theme_use('classic')

        window.resizable(False, False)
        window.mainloop()

    POLLING_DELAY = 50  # ms
    lock = threading.Lock()  # Lock for shared resources.
    finished = False

    ind = -1

    def fix(self, window):
        global finished
        with self.lock:
            finished = False
        t = threading.Thread(target=self.book, args=(window,))
        t.daemon = True
        self.check_status(window)  # Start polling.
        t.start()

    def check_status(self, window):
        with self.lock:
            if not finished:
                self.ind = self.ind + 1
                window.after(1, self.fun(self.ind, window))
                window.update_idletasks()
                window.after(self.POLLING_DELAY, self.check_status, window)  # Keep polling.
            else:
                window.destroy()

    def drawYellowBlock(self, index, window):
        widget = Label(window, bg="#1F2732", width=1, height=1)
        widget.place(x=70 + index - 1 * 22, y=350)

    def fun(self, j, window):
        self.drawYellowBlock(j, window)
        window.update_idletasks()

    def book(self, window):
        kairosBot = KairosBot(self.userId, self.password)
        window.after(2000, kairosBot.book(self.date))
        global finished
        with self.lock:
            finished = True

    def startGUI3(self):
        window = Tk()

        window.geometry("474x628")
        window.configure(bg="#FFFFFF")

        canvas = Canvas(
            window,
            bg="#FFFFFF",
            height=628,
            width=474,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)
        canvas.create_rectangle(
            0.0,
            0.0,
            474.0,
            628.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            32.0,
            32.0,
            anchor="nw",
            text="KairosBot",
            fill="#000000",
            font=("Montserrat Bold", 32 * -1)
        )

        canvas.create_rectangle(
            0.0,
            132.0,
            474.0,
            192.0,
            fill="#FAFAFA",
            outline="")

        canvas.create_text(
            32.0,
            152.0,
            anchor="nw",
            text="Prenotazione lezioni dell’intera giornata",
            fill="#000000",
            font=("Roboto", 13 * -1)
        )

        canvas.create_rectangle(
            0.0,
            132.0,
            474.0,
            133.0,
            fill="#F1F1F1",
            outline="")

        canvas.create_text(
            32.0,
            86.0,
            anchor="nw",
            text="Prenotazione in corso",
            fill="#111111",
            font=("Roboto", 16 * -1)
        )

        canvas.create_text(
            140.0,
            250.0,
            anchor="nw",
            text="Prenotazione in corso...",
            fill="#000000",
            font=("Montserrat Bold", 20 * -1)
        )

        s = ttk.Style(window)
        s.theme_use('classic')

        window.update()
        self.fix(window)

        window.mainloop()

        # update window to see animation

        # window.resizable(False, False)


if __name__ == '__main__':
    gui = GUI()
    gui.startGUI1()
